### ISSUE TITLE
alertyfy is GEEN jQuery plugin

### ISSUE THREAD

**Issue by Theo-denBlanken** [eniciodehaas/jQuery#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
http://fabien-d.github.com/alertify.js/ 
```

URL: https://github.com/eniciodehaas/jQuery/blob/master/plugin

Feedback: maar een die zonder jQuery net zo goed werkt.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by eniciodehaas** [comment]
issue opgelost
